project:
  type: website
  output-dir: docs
toc: true
website:
  title: "Natural language processing exercises"
  sidebar: 
    style: "floating"
    search: true
    contents: 
      - href: get_started.qmd
      - href: tf_idf.qmd
  page-footer: "Copyright 2024, Prof. Dr. Tim Weber" 

format:
  html:
    # theme: sandstone
    css: styles.css
    toc: true

